DROP TABLE IF EXISTS visits;
DROP TABLE IF EXISTS vet_specialties;
DROP TABLE IF EXISTS specialties;
DROP TABLE IF EXISTS vets;
DROP TABLE IF EXISTS pets;
DROP TABLE IF EXISTS pet_types;
DROP TABLE IF EXISTS owners;

CREATE TABLE owners (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(30),
    last_name  VARCHAR(30),
    address    VARCHAR(255),
    city       VARCHAR(80),
    telephone  VARCHAR(20)
);
CREATE INDEX idx_owners_last_name ON owners (last_name);

CREATE TABLE pet_types (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80)
);

CREATE TABLE pets (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(30),
    birth_date DATE,
    type_id    INTEGER NOT NULL,
    owner_id   INTEGER,
    FOREIGN KEY (type_id) REFERENCES pet_types (id),
    FOREIGN KEY (owner_id) REFERENCES owners (id)
);
CREATE INDEX idx_pets_owner_id ON pets (owner_id);

CREATE TABLE vets (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(30),
    last_name  VARCHAR(30)
);

CREATE TABLE specialties (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80)
);

CREATE TABLE vet_specialties (
    vet_id       INTEGER NOT NULL,
    specialty_id INTEGER NOT NULL,
    FOREIGN KEY (vet_id) REFERENCES vets (id),
    FOREIGN KEY (specialty_id) REFERENCES specialties (id)
);

CREATE TABLE visits (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id      INTEGER,
    visit_date  DATE,
    description VARCHAR(255),
    FOREIGN KEY (pet_id) REFERENCES pets (id)
);
CREATE INDEX idx_visits_pet_id ON visits (pet_id);
